name: alisyed_com
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  responsive_framework: ^0.1.0
  lottie: ^1.0.1
  flare_flutter: ^3.0.0
  url_strategy: ^0.2.0
  auto_size_text: ^2.1.0
  mouse_parallax: ^1.1.0
  animated_text_kit: ^4.2.1








dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    # - images/a_dot_burr.jpeg
    - assets/images/myPortraits/portraitDistortion.png
    - lib/assets/animations/18123-developer.json
    - lib/assets/pngs/
    - lib/assets/pngs/socialMedia_pngs/
    - lib/assets/pngs/work1bg_stars.jpg

  
  
    


